### ISSUE TITLE
[BUG] Encre UI: UI Render Failure at `SyntaxText.tsx` when creating new node

### ISSUE THREAD

**Issue by VictorS67** [VictorS67/encre#114]
### What happened?

When I use context menu `Add Node` to add a new node, the node content body is blank. The console shows error log at `SyntaxText.tsx`. The error log is shown below

### What was the expected behavior?

The node content should appear correctly.

### Describe your environment

MacOS 10.14.6

node version 20.15.0

### Relevant log output

```shell
chunk-5JCKZDCJ.js:14016 The above error occurred in one of your React components:

    at Lazy
    at div
    at div
    at Suspense
    at http://localhost:3001/src/components/descriptors/CodeDescriptor.tsx?t=1726100897014:16:107
    at div
    at http://localhost:3001/node_modules/.vite/deps/chunk-IYL5AZN3.js?v=504eb605:1666:49
    at div
    at KnownNodeContentBody (http://localhost:3001/src/components/NodeContentBody.tsx?t=1726100897014:94:40)
    at http://localhost:3001/src/components/NodeContentBody.tsx?t=1726100897014:32:66
    at ErrorBoundary (http://localhost:3001/node_modules/.vite/deps/react-error-boundary.js?v=504eb605:18:5)
    at div
    at div
    at div
    at http://localhost:3001/node_modules/.vite/deps/chunk-IYL5AZN3.js?v=504eb605:1666:49
    at http://localhost:3001/src/components/VisualNode.tsx?t=1726100897014:411:91
    at div
    at http://localhost:3001/node_modules/.vite/deps/chunk-IYL5AZN3.js?v=504eb605:1666:49
    at MyVisualNode (http://localhost:3001/src/components/VisualNode.tsx?t=1726100897014:272:154)
    at ErrorBoundary (http://localhost:3001/node_modules/.vite/deps/react-error-boundary.js?v=504eb605:18:5)
    at DraggableNode (http://localhost:3001/src/components/DraggableNode.tsx?t=1726100897014:18:33)
    at div
    at div
    at div
    at http://localhost:3001/node_modules/.vite/deps/chunk-IYL5AZN3.js?v=504eb605:1666:49
    at DndContext2 (http://localhost:3001/node_modules/.vite/deps/@dnd-kit_core.js?v=504eb605:24260:5)
    at div
    at NodeCanvas (http://localhost:3001/src/components/NodeCanvas.tsx?t=1726100897014:122:30)
    at ErrorBoundary (http://localhost:3001/node_modules/.vite/deps/react-error-boundary.js?v=504eb605:18:5)
    at NodeGraphBuilder (http://localhost:3001/src/components/NodeGraphBuilder.tsx?t=1726100897014:23:31)
    at div
    at Pane (http://localhost:3001/src/components/Pane.tsx:11:24)
    at div
    at http://localhost:3001/node_modules/.vite/deps/chunk-IYL5AZN3.js?v=504eb605:1666:49
    at SplitPane (http://localhost:3001/src/components/SplitPane.tsx:68:29)
    at div
    at div
    at http://localhost:3001/node_modules/.vite/deps/chunk-IYL5AZN3.js?v=504eb605:1666:49
    at EncreStudio (http://localhost:3001/src/components/EncreStudio.tsx?t=1726100897014:47:31)
    at AppInner (http://localhost:3001/src/App.tsx?t=1726100897014:52:45)
    at ErrorBoundary (http://localhost:3001/node_modules/.vite/deps/react-error-boundary.js?v=504eb605:18:5)
    at QueryClientProvider (http://localhost:3001/node_modules/.vite/deps/@tanstack_react-query.js?v=504eb605:2585:3)
    at RecoilRoot_INTERNAL (http://localhost:3001/node_modules/.vite/deps/recoil.js?v=504eb605:24375:3)
    at RecoilRoot (http://localhost:3001/node_modules/.vite/deps/recoil.js?v=504eb605:24493:5)
    at App

React will try to recreate this component tree from scratch using the error boundary you provided, ErrorBoundary.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by VictorS67** [comment]
This issue is fixed.

It occurs at `utils/monacoEditor.ts`, where it imports `dataTypes` from backend. DO NOT import any constant from backend, otherwise this issue will occurs again.
