### ISSUE TITLE
[BUG] Fail to run webapp on windows

### ISSUE THREAD

**Issue by AlveinTeng** [VictorS67/encre#128]
### What happened?

When trying to run webapp on windows, got an error:

NetworkError: Failed to execute 'importScripts' on 'WorkerGlobalScope': The script at 'http://localhost:3001/kcab/kcab.worker.dev.js' failed to load.
    at importScriptsWithRetry (browser-server.js:8:5)
    at browser-server.js:25:15

### What was the expected behavior?

Should not get such error

### Describe your environment

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AlveinTeng** [comment]
Current issue is now fixed.

- First modify packages/internal/bin/build-browser to make sure that when running on windows, files are directly built to the target directory: packages/app/kcab/
- Update packages/internal/webpack/webpack.browser.config.js accordingly.
