### ISSUE TITLE
[BUG] Encre Server: ERROR InternalError: nodesService.getNodeBody: this.node.data.getAttributes is not a function

### ISSUE THREAD

**Issue by VictorS67** [VictorS67/encre#134]
### What happened?

When using `globalNodeRegistry` to create NodeImpl, an internal error occurs: 

```bash
ERROR InternalError: nodesService.getNodeBody: this.node.data.getAttributes is not a function
```

Code and Error logs are shown below. I assume this error is occurring when the attribute value `node` is only a JSON object.

### What was the expected behavior?

The NodeImpl should be created without errors.

### Describe your environment

MacOS 10.14.6, Node v20.15.0

### Relevant log output

```shell
ERROR InternalError: nodesService.getNodeBody: this.node.data.getAttributes is not a function
    at Object.getNodeBody (file:///encre/packages/server/dist/services/nodes/index.js:82:15)
    at getNodeBody (file:///encre/packages/server/dist/controllers/nodes/index.js:50:45)
    at Layer.handle [as handle_request] (/encre/node_modules/express/lib/router/layer.js:95:5)
    at next (/encre/node_modules/express/lib/router/route.js:149:13)
    at Route.dispatch (/encre/node_modules/express/lib/router/route.js:119:3)
    at Layer.handle [as handle_request] (/encre/node_modules/express/lib/router/layer.js:95:5)
    at /encre/node_modules/express/lib/router/index.js:284:15
    at Function.process_params (/encre/node_modules/express/lib/router/index.js:346:12)
    at next (/encre/node_modules/express/lib/router/index.js:280:10)
    at Function.handle (/encre/node_modules/express/lib/router/index.js:175:3) {
  code: 500
}
```

### Relevant screenshots

nodesService.getNodeBody:

<img width="556" alt="Screen Shot 2024-09-23 at 08 45 26" src="https://github.com/user-attachments/assets/7fe6a6eb-a4cc-42da-9306-f42c2de00cc3">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by VictorS67** [comment]
This is issue has been fixed in https://github.com/VictorS67/encre/pull/98. Now we can use `createLoadImpl` or `createDynamicLoadImpl` for the cases that nodes are simple JSON objects.
